### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by denys119** [Kingwl/monaco-volar#12]
Hello!

I tried @dannysmc95's project in Vue 3 and everything worked fine but when I try to implement the same code in Nuxt 3 (rc-13) something is not working.

I got this error in console on localhost 

chunk-ZIRKYQSR.js?v=154af42d:1253 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'VSCODE_TEXTMATE_DEBUG')
    at node_modules/.pnpm/monaco-textmate@3.0.1_onigasm@2.2.5/node_modules/monaco-textmate/dist/debug.js
![Untitled](https://user-images.githubusercontent.com/72434901/201480994-9f66633b-1c52-4b88-808c-0c431ea0c8b8.png)

I have the same project here on Stackblitz for reproduction.

https://github.com/denys119/node-ujgstf

Thank you in advance!

**Comment by danut99** [comment]
I got the same problem. Any fix for this problem?

**Comment by AdrianSK75** [comment]
Hello! I found the same error in my project. Exists any fix for this issue?

**Comment by Sight-wcg** [comment]
related https://github.com/nuxt/framework/issues/2797
```
import monacoEditor from 'vite-plugin-monaco-editor';

export default defineNuxtConfig({
  vite: {
    define: {
      // Fix broken dependencies of monaco-textmate
      'process.env': {},
    },
    plugins: [monacoEditor()],
  },
});
```
