### ISSUE TITLE
Upgrade `monaco-editor-core` to 0.35.1

### ISSUE THREAD

**Issue by randomVariable2000** [Kingwl/monaco-volar#14]
## Upgrade `monaco-editor-core` to 0.35.1
Hi! Thanks for your great job. 

We need `glyphMargin` and `renderMarginRevertIcon` feature only work in `0.34.0`.

**Comment by johnsoncodehk** [comment]
Close as resolved

**Comment by randomVariable2000** [comment]
thanks
