### ISSUE TITLE
How to addExtraLib 

### ISSUE THREAD

**Issue by Deuscx** [Kingwl/monaco-volar#15]
When addExtraLib vueuse type , but no type definition when hover

```ts
import vueuseTypes from '@vueuse/core/index.d.ts?raw';

// ....
  const vueUsemodel = getOrCreateModel(Uri.parse("file:///vueuse.d.ts"), "vue", vueuseTypes);
  languages.vue.vueDefaults.addExtraLib(
    vueUsemodel.uri.fsPath as any,
    vueUsemodel.getValue()
  );

```

<img width="547" alt="image" src="https://user-images.githubusercontent.com/48537979/213099458-d8830082-ec5c-4beb-9310-2aafb3d06c70.png">

**Comment by Sight-wcg** [comment]
```ts
import vueuseCoreContent from '@vueuse/core/index.d.ts?raw'
import * as path from 'typesafe-path'

  // '%40' -> '@'
  const vueuseUrl = Uri.parse('file:///node_modules/%40vueuse/core/index.d.ts');
  const vueuseModel = getOrCreateModel(vueuseUrl, undefined, vueuseCoreContent);
  languages.vue.vueDefaults.addExtraLib(vueUseModel.uri.fsPath as path.OsPath, vueuseModel.getValue() );
```

![image](https://user-images.githubusercontent.com/26325820/213141416-a1327f80-f980-48f4-b07a-627868dfbc6c.png)

**Comment by Deuscx** [comment]
> ```ts
> import vueuseCoreContent from '@vueuse/core/index.d.ts?raw'
> import * as path from 'typesafe-path'
> 
>   // '%40' -> '@'
>   const vueuseUrl = Uri.parse('file:///node_modules/%40vueuse/core/index.d.ts');
>   const vueuseModel = getOrCreateModel(vueuseUrl, undefined, vueuseCoreContent);
>   languages.vue.vueDefaults.addExtraLib(vueUseModel.uri.fsPath as path.OsPath, vueuseModel.getValue() );
> ```

It works for me. Thx

**Comment by oceangravity** [comment]
Hi, I attempted to use the addExtraLib method with the suggested fix, but it seems to no longer work. Could anyone kindly assist me with this issue? Thank you in advance!

**Comment by oodavid** [comment]
@oceangravity - `monaco` 0.55.0 made a breaking change that looks related:

https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0550

I'll see if I can replicate
