### ISSUE TITLE
language service not work on demo page

### ISSUE THREAD

**Issue by troy351** [Kingwl/monaco-volar#6]
I don't see any language service related features on https://kingwl.github.io/monaco-volar/
Only `Syntax Highlight` and `Format Document` works.
What am I missing?

**Comment by Kingwl** [comment]
It may take a while

<img width="327" alt="image" src="https://user-images.githubusercontent.com/6831019/181212658-ed271837-f0ba-4983-b0b4-27f6d77e03ad.png">

**Comment by troy351** [comment]
It's weird, I cleared browser cache and waited at least 10min with Chrome and Firefox.
Still nothing

**Comment by Kingwl** [comment]
"a while" seems does not a lot of time.

<img width="1417" alt="image" src="https://user-images.githubusercontent.com/6831019/181413843-71113ef5-1aec-4d14-8515-6ad3c03a375e.png">

Would you mind to share a screenshot or short video for what happened in your browser?

**Comment by troy351** [comment]
Network Panel
![image](https://user-images.githubusercontent.com/8372385/181414359-26c85bea-f582-4ab7-b93f-bdfa60673b71.png)

After Loaded abort 5min later

https://user-images.githubusercontent.com/8372385/181415678-1f95c11e-4e75-47ac-b222-0b534c1075d0.mp4

**Comment by Kingwl** [comment]
It looks weird.  

Would you mind try open an chrome in private mode(to avoid chrome extensions)?
Or share some environment？eg: 
- OS
- Chrome

@johnsoncodehk Any thought?

**Comment by troy351** [comment]
- Windows 10 + Chrome/Chrome Private/Edge/Firefox **NOT Working**
- Windows 11 + Chrome **NOT Working**
- macOS + Chrome **Working**

**Comment by Kingwl** [comment]
I guess it's caused by path separator? I'll take a look soon (After find a Windows PC).

**Comment by dannysmc95** [comment]
Just adding, there is no language features at all for me either.

**Comment by cjboy76** [comment]
same

**Comment by Kingwl** [comment]
I ordered an intel nuc for testing, should be able to arrive soon :XD.

**Comment by troy351** [comment]
such an expensive bug😵

**Comment by wj453245456** [comment]
mark
